<select name="order" class="form-control" id="formOrder">
    <?
    for ($i = 1; $i <= $count; $i++) {
          $selected = '';
          if ($one_order) {
               $selected = ($one_order == $i) ? 'selected = "selected"' : '';
          } else {
               $selected = ($count_for == $i) ? 'selected = "selected"' : '';
        }?>
        <option value="<?=$i;?>" <?=$selected?> > <?=$i;?></option>
    <? }?>
</select>