     <? $this->load->view('admin/inc/head'); ?>
     <script src="<?=site_url('/www/js/admin/categories.js');?>"></script>
     <script src="http://malsup.github.com/jquery.form.js"></script> 
</head>
<body>
     <? $this->load->view('admin/inc/top'); ?>
     <div class="container main">
          <? if (isset($message) && $message) { ?>
              <div class="alert alert-info" role="alert"><?=$message;?></div>
          <? } ?>

          <button type="button" class="btn btn-default" onclick="return show_hide($('div#add-edit-form'));">Добавить категорию</button>
          <span class="message" id="message"></span>
          <div id="add-edit-form" class="add-edit-form">
                 <? $this->load->view('admin/categories/add_edit_form.phtml'); ?>
          </div>

          <div id="list">
               <? $this->load->view('admin/categories/list.phtml'); ?>
          </div>
     </div>
     <? $this->load->view('admin/inc/footer');?>
</body>
</html>